content(String projectName) {
  return """
/// This file has been generated by Flutter Architect.
/// Flutter Architect is a tool that generates boilerplate code for your Flutter projects.
/// Flutter Architect was created @SayNode Operations AG by Yann Marti and Francesco Romeo
/// https://saynode.ch
/// 

import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:get/get.dart';
import 'package:$projectName/page/error/controller/error_controller.dart';


import '../../services/theme_service.dart';
import '../../theme/constants.dart';
import '../../theme/custom_themes.dart';
import '../../util/util.dart';

class ErrorPage extends GetView<ErrorController> {
  const ErrorPage({super.key});

  @override
  Widget build(BuildContext context) {
    ProjectThemeName ProjectThemeName = Get.put(ThemeService()).ProjectThemeName;
    Get.put(ErrorController());

    return Scaffold(
      body: Center(
        child: Container(
          width: getRelativeWidth(350),
          padding: EdgeInsets.only(
              top: getRelativeHeight(29),
              bottom: getRelativeHeight(25),
              right: getRelativeWidth(31.5),
              left: getRelativeWidth(31.5)),
          decoration: BoxDecoration(
            color: const Color(0xff1c1d21),
            borderRadius: BorderRadius.circular(20),
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              SvgPicture.asset("assets/icons/warning_icon.svg"),
              SizedBox(height: getRelativeHeight(28)),
              Text(
                "Oops...".tr,
                style: TextStyle(color: Colors.black), //TODO Add theme color for background,
              ),
              SizedBox(height: getRelativeHeight(21)),
              Text(
                "Sorry, we're having an issue but it should be fixed shortly. Please contact us at [email address] if you keep having problems."
                    .tr,
                style: TextStyle(color: Colors.black), //TODO Add theme color for text,
                textAlign: TextAlign.center,
              ),
              SizedBox(
                height: getRelativeHeight(21),
              ),
              Text(
                "Please, try to restart the app.".tr,
                style: TextStyle(color: Colors.black), //TODO Add theme color for background,
                textAlign: TextAlign.center,
              ),
            ],
          ),
        ),
      ),
      backgroundColor: ProjectThemeName.gameOfLifeNeutralBackgroundColor,
    );
  }
}


  """;
}
