content(String projectName) {
  return """
/// This file has been generated by Flutter Architect.
/// Flutter Architect is a tool that generates boilerplate code for your Flutter projects.
/// Flutter Architect was created @SayNode Operations AG by Yann Marti and Francesco Romeo
/// https://saynode.ch
///
library;

import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:get/get.dart';
import '../../theme/theme.dart';
import 'controller/error_controller.dart';

import '../../util/util.dart';

class ErrorPage extends GetView<ErrorController> {
  const ErrorPage({super.key});

  @override
  Widget build(BuildContext context) {
    Get.put(ErrorController());

    return Scaffold(
      body: Center(
        child: Container(
          width: getRelativeWidth(350), //TODO Add correct number from design
          padding: EdgeInsets.only(
              top: getRelativeHeight(29), //TODO Add correct number from design
              bottom: getRelativeHeight(25), //TODO Add correct number from design
              right: getRelativeWidth(31.5), //TODO Add correct number from design
              left: getRelativeWidth(31.5),), //TODO Add correct number from design
          decoration: BoxDecoration(
            color: const Color(0xff1c1d21),
            borderRadius: BorderRadius.circular(20), //TODO Add correct number from design
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              SvgPicture.asset('assets/icons/warning_icon.svg'),
              SizedBox(height: getRelativeHeight(28)), //TODO Add correct number from design
              Text(
                'Oops...'.tr,
                style: const TextStyle(
                    color: Colors.black,), //TODO Add correct theme color
              ),
              SizedBox(height: getRelativeHeight(21)), //TODO Add correct number from design
              Text(
                "Sorry, we're having an issue but it should be fixed shortly. Please contact us at [email address] if you keep having problems."
                    .tr,
                style: const TextStyle(
                    color: Colors.black,), //TODO Add correct theme color
                textAlign: TextAlign.center,
              ),
              SizedBox(
                height: getRelativeHeight(21), //TODO Add correct number from design
              ),
              Text(
                'Please, try to restart the app.'.tr,
                style: const TextStyle(
                    color: Colors.black,), //TODO Add correct theme color
                textAlign: TextAlign.center,
              ),
            ],
          ),
        ),
      ),
      backgroundColor: CustomTheme.dark.electric,//TODO Add correct theme color
    );
  }
}
  """;
}
