// This file has been automatically generated by Flutter Architect.
//
// Flutter Architect is a tool that generates boilerplate code for your Flutter projects.
// Flutter Architect was created at SayNode Operations AG by Yann Marti, Francesco Romeo and Pedro Gonçalves.
//
// https://saynode.ch

import 'package:get/get.dart';

import 'secure_storage_service.dart';
import 'shared_storage_service.dart';

class StorageService extends GetxService {
  SecureStorageService get secure => Get.find<SecureStorageService>();
  SharedStorageService get shared => Get.find<SharedStorageService>();

  Future<void> init() async {
    await secure.init();
    await shared.init();
  }
}
