name: project_initialization_tool
description: A command-line application.
version: 0.0.1


environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  dcli: ^3.2.0
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
