name: testing
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  connectivity_plus: ^6.0.3
  firebase_core: ^3.0.0
  firebase_crashlytics: ^4.0.0
  flutter:
    sdk: flutter
  flutter_network_connectivity: ^0.0.6
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  is_first_run: ^1.0.0
  package_info_plus: ^8.0.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - asset/

  uses-material-design: true
