name: testing
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  get: ^4.6.6
  google_sign_in: ^6.2.1
  http: ^1.2.1
  is_first_run: ^1.0.0
  shared_preferences: ^2.2.3
  sign_in_with_apple: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - asset/

  uses-material-design: true
