// This file has been automatically generated by Flutter Architect.
//
// Flutter Architect is a tool that generates boilerplate code for your Flutter projects.
// Flutter Architect was created at SayNode Operations AG by Yann Marti, Francesco Romeo and Pedro Gonçalves.
//
// https://saynode.ch

class AuthResponse {
  AuthResponse({
    required this.result,
    required this.accessToken,
    required this.message,
    required this.status,
    required this.success,
  });

  factory AuthResponse.fromJson(Map<String, dynamic> json) {
    return AuthResponse(
      accessToken:
          (json['result'] as Map<String, dynamic>)['access_token'] as String? ??
              '',
      result: json['result'] as Map<String, dynamic>? ?? <String, dynamic>{},
      message: json['message'] as String,
      status: json['status'] as int,
      success: json['success'] as bool,
    );
  }
  final String accessToken;
  final Map<String, dynamic> result;
  final String message;
  final int status;
  final bool success;

  @override
  String toString() {
    return 'AuthResponse(accessToken: $accessToken, message: $message, status: $status, success: $success)';
  }
}
