// This file has been automatically generated by Flutter Architect.
//
// Flutter Architect is a tool that generates boilerplate code for your Flutter projects.
// Flutter Architect was created at SayNode Operations AG by Yann Marti, Francesco Romeo and Pedro Gonçalves.
//
// https://saynode.ch

// This file has been generated by Flutter Architect.
// Flutter Architect is a tool that generates boilerplate code for your Flutter projects.
// Flutter Architect was created @SayNode Operations AG by Yann Marti and Francesco Romeo
// https://saynode.ch
//

import 'package:get/get.dart';

class ErrorController extends GetxController {
  final RxBool restarting = false.obs;

  // restartApp(BuildContext context) async {
  //   restarting.value = true;
  //   await RestartWidget.restartApp(context);
  //   restarting.value = false;
  // }
}
