// This file has been automatically generated by Flutter Architect.
//
// Flutter Architect is a tool that generates boilerplate code for your Flutter projects.
// Flutter Architect was created at SayNode Operations AG by Yann Marti, Francesco Romeo and Pedro Gonçalves.
//
// https://saynode.ch

// ignore_for_file: invalid_use_of_protected_member

import 'package:flutter/material.dart';
import 'package:get/get.dart';

import '../util/constants.dart';

class LoggerService extends GetxService {
  final RxList<Widget> _logs = <Widget>[].obs;
  final bool devMode = Constants.devMode;

  void log(String? message, {StackTrace? stackTrace, dynamic error}) {
    if (devMode) {
      if (message != null) {
        debugPrint(message);
        _addEvent(message);
      }
      if (error != null) {
        debugPrint(error.toString());
        _addEvent(error.toString());
      }
      if (stackTrace != null) {
        debugPrint(stackTrace.toString());
        _addEvent(stackTrace.toString());
      }
    }
  }

  void _addEvent(dynamic event) {
    _logs.value.add(
      Text(
        '=> $event',
        style: const TextStyle(
          color: Colors.white,
          fontSize: 12,
        ),
      ),
    );
  }

  void show() {
    Get.dialog<Widget>(
      Card(
        elevation: 6,
        color: Colors.black87,
        clipBehavior: Clip.antiAlias,
        child: SizedBox(
          width: MediaQuery.of(Get.overlayContext!).size.width,
          height: 200,
          child: Column(
            children: <Widget>[
              const Padding(
                padding: EdgeInsets.all(8),
                child: Text(
                  'Logs',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 16,
                  ),
                ),
              ),
              Expanded(
                child: Obx(() {
                  return ListView(
                    reverse: true,
                    padding: const EdgeInsets.all(6),
                    children: _logs.value.reversed.toList(),
                  );
                }),
              ),

              //clear logs button
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                children: <Widget>[
                  TextButton(
                    // ignore: inference_failure_on_generic_invocation
                    onPressed: Get.back,
                    child: const Text(
                      'Close',
                      style: TextStyle(
                        color: Colors.white,
                        fontSize: 16,
                      ),
                    ),
                  ),
                  TextButton(
                    onPressed: () {
                      _logs.value.clear();
                      _logs.refresh();
                    },
                    child: const Text(
                      'Clear Logs',
                      style: TextStyle(
                        color: Colors.white,
                        fontSize: 16,
                      ),
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}
