// This file has been automatically generated by Flutter Architect.
//
// Flutter Architect is a tool that generates boilerplate code for your Flutter projects.
// Flutter Architect was created at SayNode Operations AG by Yann Marti, Francesco Romeo and Pedro Gonçalves.
//
// https://saynode.ch

// ignore_for_file: cascade_invocations
import 'package:get/get.dart';

import 'auth_service.dart';

import 'api_service.dart';
import 'storage/secure_storage_service.dart';
import 'storage/shared_storage_service.dart';
import 'storage/storage_service.dart';

import 'logger_service.dart';

class MainBindings extends Bindings {
  @override
  Future<void> dependencies() async {
    //inject services and controllers
    _injectServices();
    _injectControllers();
  }

  void _injectServices() {
    //Services injection

    Get.lazyPut(AuthService.new);

    Get.lazyPut(APIService.new);
    Get.lazyPut(SharedStorageService.new);
    Get.lazyPut(SecureStorageService.new);
    Get.lazyPut(StorageService.new);

    Get.lazyPut(LoggerService.new);
  }

  void _injectControllers() {
    //Controllers injection
  }
}
