// This file has been automatically generated by Flutter Architect.
//
// Flutter Architect is a tool that generates boilerplate code for your Flutter projects.
// Flutter Architect was created at SayNode Operations AG by Yann Marti, Francesco Romeo and Pedro Gonçalves.
//
// https://saynode.ch

import 'package:get/get.dart';

import 'logger_service.dart';

class MainBindings extends Bindings {
  @override
  Future<void> dependencies() async {
    //inject services and controllers
    _injectServices();
    _injectControllers();
  }

  void _injectServices() {
    //Services injection

    Get.lazyPut(LoggerService.new);
  }

  void _injectControllers() {
    //Controllers injection
  }
}
